In [2]:
##
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import geopandas
import geopandas as gpd
import matplotlib.pyplot as plt
import pyproj
import math
import os

In [3]:
oldcard1=pd.read_csv(r'F:\扬州\oldcard1_11.csv',)
oldcard1

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期
0,0,9616900720343197,6,20220611184643,1.0,160,16,104643,20220611
1,1,9616900720229892,6,20220611184819,1.0,160,16,104819,20220611
2,2,9616900722020003,6,20220611184837,1.0,160,16,104837,20220611
3,3,9616900721987090,101,20220611201457,1.6,160,16,121457,20220611
4,4,9616900711049089,101,20220611203704,0.0,160,16,123704,20220611
...,...,...,...,...,...,...,...,...,...
46663,46663,9616900722268015,101,20220612014737,1.6,270,27,934737,20220611
46664,46664,9616900722196402,101,20220612015350,1.6,270,27,935350,20220611
46665,46665,9616900720382304,101,20220612015539,1.6,270,27,935539,20220611
46666,46666,9616900722246864,6,20220612020146,0.0,270,27,940146,20220611
46667,46667,9616900721772135,6,20220612020151,0.0,270,27,940151,20220611

In [9]:
oldcard1.sort_values(by='时间')

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期
1162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611
1866,1866,9616900721991115,6,20220611130132,1.0,880,88,50132,20220611
1867,1867,9616900730081595,6,20220611130529,1.0,880,88,50529,20220611
44791,44791,9616900720346426,11,20220611130550,0.0,6270,627,50550,20220611
14314,14314,9616900722242310,6,20220611131021,1.0,880,88,51021,20220611
...,...,...,...,...,...,...,...,...,...
1618,1618,9616900101114963,101,20220612061548,1.6,551,55,981548,20220611
21404,21404,9616900722011730,11,20220612061601,0.0,180,18,981601,20220611
30231,30231,9616900720110302,101,20220612061700,1.6,200,20,981700,20220611
25259,25259,9616900722227009,6,20220612062146,1.0,661,66,982146,20220611
6748,6748,9616900720319792,101,20220612063952,0.0,601,60,983952,20220611

In [4]:
#线路索引
IDSY = oldcard1.drop_duplicates(subset=['线路编号'],keep='first')
IDSY.sort_values(by='线路编号',inplace=True)
IDSY.reset_index(drop=True,inplace=True) 
IDSY

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611
...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611

In [69]:
##以30分钟为粒度统计老年卡和其他卡
##在此基础上新建统计框

IDSY['段开始时间']=None
IDSY['老年卡客运量']=0
IDSY['其他卡客运量']=0
IDSY['总客运量']=0


t1=40000+0*10000
t2=40000+0*10000+3000
#t2=i*100000+6000
##筛选时间段内的所有刷卡数据
listt=[]   
for g in range(0,len(oldcard1)):
    TIME=int(oldcard1['时间'].iloc[g])
    if TIME>=t1 and TIME<=t2:
        listt.append(g)
oldcard2=oldcard1.loc[listt,:]
oldcard2.reset_index(drop=True,inplace=True) 
print('oldcard2')
print(oldcard2)
##按照线路名统计每条线上的刷卡数据
for i in range(0,len(IDSY)):
    IDSY['段开始时间'].iloc[i]=t1
    tsum=0
    list2=[]
    for k in range(0,len(oldcard2)):
        id1=oldcard2['线路编号'].iloc[k]
        id2=IDSY['线路编号'].iloc[i] 
        
        if id1==id2:                  
            tsum = tsum+1
            IDSY['总客运量'].iloc[i]=tsum
            list2.append(k)
    oldcard3=oldcard2.loc[list2,:]
    #print('oldcard3')
    #print(oldcard3)
    ##线路相同的情况下的刷卡类型统计
    oldcard4=oldcard3[(oldcard3['卡类型']==6)|(oldcard3['卡类型']==11)]
    #print('oldcard4')
    #print(oldcard4)
    osum=len(oldcard4)
    IDSY['老年卡客运量'].iloc[i]=osum
    fosum=tsum-osum
    IDSY['其他卡客运量'].iloc[i]=fosum
ALLIDSY=IDSY       
ALLIDSY

oldcard2
Empty DataFrame
Columns: [Unnamed: 0, 卡号, 卡类型, 交易时间需减去8小时, 交易金额, 线路号, 线路编号, 时间, 日期]
Index: []

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,40000,0,0,0
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611,40000,0,0,0
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611,40000,0,0,0
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611,40000,0,0,0
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611,40000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611,40000,0,0,0
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611,40000,0,0,0
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611,40000,0,0,0
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611,40000,0,0,0
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,40000,0,0,0

In [70]:
##以30分钟为粒度统计老年卡和其他卡
##在此基础上新建统计框
for i in range(1,12):
    t1=40000+i*10000
    t2=40000+i*10000+3000
    #t2=i*100000+6000
    ##筛选时间段内的所有刷卡数据
    listt=[]   
    for g in range(0,len(oldcard1)):
        TIME=int(oldcard1['时间'].iloc[g])
        if TIME>=t1 and TIME<=t2:
            listt.append(g)
    oldcard2=oldcard1.loc[listt,:]
    oldcard2.reset_index(drop=True,inplace=True) 
    print('oldcard2')
    print(oldcard2)
    IDSY['段开始时间']=0
    IDSY['老年卡客运量']=0
    IDSY['其他卡客运量']=0
    IDSY['总客运量']=0
    ##按照线路名统计每条线上的刷卡数据
    for i in range(0,len(IDSY)):

        IDSY['段开始时间'].iloc[i]=t1
        tsum=0
        list2=[]
        for k in range(0,len(oldcard2)):
            id1=oldcard2['线路编号'].iloc[k]
            id2=IDSY['线路编号'].iloc[i] 
            if id1==id2:                  
                tsum = tsum+1
                IDSY['总客运量'].iloc[i]=tsum
                list2.append(k)
        oldcard3=oldcard2.loc[list2,:]
        #print('oldcard3')
        #print(oldcard3)
        ##线路相同的情况下的刷卡类型统计
        oldcard4=oldcard3[(oldcard3['卡类型']==6)|(oldcard3['卡类型']==11)]
      ##  print('oldcard4')
        #print(oldcard4)
        osum=len(oldcard4)
        IDSY['老年卡客运量'].iloc[i]=osum
        fosum=tsum-osum
        IDSY['其他卡客运量'].iloc[i]=fosum
    ALLIDSY=ALLIDSY.append(IDSY)      
ALLIDSY

oldcard2
    Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0         1163  9616900721791451  101  20220611131034   2.4  6220   622
1         1610  9616900721753777  101  20220611131126   1.6   710    71
2         1611  9616900720344603    6  20220611132126   1.0   710    71
3         1866  9616900721991115    6  20220611130132   1.0   880    88
4         1867  9616900730081595    6  20220611130529   1.0   880    88
5         1868  9616900722147137    6  20220611131522   1.0   880    88
6         1869  9616900722207916    6  20220611131528   1.0   880    88
7         8636  9616900720229560    6  20220611132625   1.0   880    88
8         8637  9616900722096778    6  20220611132804   1.0   880    88
9        10096  9616900722020389    6  20220611132111   1.0   150    15
10       10097  9616900721708619    6  20220611132146   1.0   150    15
11       10098  9616900722187269    6  20220611132254   1.0   150    15
12       10099  9616900760083448  101  20220611132257   1.6   150    15
13       10100  9616900730081434    6  20220611132318   1.0   150    15
14       10101  9616900721606085    6  20220611132331   1.0   150    15
15       10102  9616900721575643   11  20220611132543   0.0   150    15
16       10103  9616900720396597    6  20220611132612   1.0   150    15
17       13505  9616900730123177    6  20220611132723   1.0  2390   239
18       14314  9616900722242310    6  20220611131021   1.0   880    88
19       14315  9616900720127933  101  20220611131112   1.6   880    88
20       17669  9616900721994624    6  20220611132911   1.0  1070   107
21       22440  9616900730125772    6  20220611132644   1.0  2880   288
22       22441  9616900730073085    6  20220611132712   1.0  2880   288
23       22442  9616900730126579    6  20220611132742   1.0  2880   288
24       22443  9616900716077434  101  20220611132807   1.6  2880   288
25       32266  9616900722138203   11  20220611131626   0.0  2180   218
26       32267  9616900730131557    6  20220611131643   1.0  2180   218
27       32324  9616900722264602  101  20220611132158   1.6  2180   218
28       32325  9616900730137256    6  20220611132845   1.0  2180   218
29       39512  9616900721517072   11  20220611132946   0.0   150    15
30       40185  9616900730068343   11  20220611132839   0.0  2370   237
31       40186  9616900730125808    6  20220611132841   1.0  2370   237
32       44791  9616900720346426   11  20220611130550   0.0  6270   627
33       44792  9616900730061451   11  20220611131103   0.0  6270   627
34       44793  9616900720097536  101  20220611131325   2.4  6270   627
35       44794  9616900730045609   11  20220611131357   0.0  6270   627
36       44795  9616900730135458    6  20220611132303   1.5  6270   627
37       44796  9616900730135463    6  20220611132307   1.5  6270   627

       时间        日期
0   51034  20220611
1   51126  20220611
2   52126  20220611
3   50132  20220611
4   50529  20220611
5   51522  20220611
6   51528  20220611
7   52625  20220611
8   52804  20220611
9   52111  20220611
10  52146  20220611
11  52254  20220611
12  52257  20220611
13  52318  20220611
14  52331  20220611
15  52543  20220611
16  52612  20220611
17  52723  20220611
18  51021  20220611
19  51112  20220611
20  52911  20220611
21  52644  20220611
22  52712  20220611
23  52742  20220611
24  52807  20220611
25  51626  20220611
26  51643  20220611
27  52158  20220611
28  52845  20220611
29  52946  20220611
30  52839  20220611
31  52841  20220611
32  50550  20220611
33  51103  20220611
34  51325  20220611
35  51357  20220611
36  52303  20220611
37  52307  20220611
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             43  9616900730044189   11  20220611142552   0.0  6120   612
1             55  9616900720183264   11  20220611141921   0.0   860    86
2             56  9616900720179147   11  20220611142229   0.0   860    86
3             78  9616900722271059  101  20220611142234   1.6   860    86
4             79  9616900722279805   11  20220611142350   0.0   860    86
...          ...               ...  ...             ...   ...   ...   ...
1340       46305                 0  101  20220611140202   1.6   500    50
1341       46306  9616900722139513   11  20220611140927   0.0   500    50
1342       46307  9616900721643900    6  20220611141253   1.0   500    50
1343       46389  9616900722054991    6  20220611141154   1.0   780    78
1344       46635  9616900721585747   11  20220611142717   0.0  3130   313

         时间        日期
0     62552  20220611
1     61921  20220611
2     62229  20220611
3     62234  20220611
4     62350  20220611
...     ...       ...
1340  60202  20220611
1341  60927  20220611
1342  61253  20220611
1343  61154  20220611
1344  62717  20220611

[1345 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             44  9616900730046909    6  20220611150536   1.5  6120   612
1             45  9616900730128016    6  20220611151721   1.5  6120   612
2             58  9616900722089648   11  20220611151349   0.0    80     8
3             97  9616900722091654   11  20220611151415   0.0  3360   336
4             98  9616900720190734   11  20220611151757   0.0  3360   336
...          ...               ...  ...             ...   ...   ...   ...
2565       46529  9616900722208447    6  20220611152904   1.0   380    38
2566       46636  9616900720410124   11  20220611151647   0.0  3130   313
2567       46637  9616900721610859   11  20220611151650   0.0  3130   313
2568       46638  9616900720343245    6  20220611151800   0.5  3130   313
2569       46639  9616900720045290   11  20220611152117   0.0  3130   313

         时间        日期
0     70536  20220611
1     71721  20220611
2     71349  20220611
3     71415  20220611
4     71757  20220611
...     ...       ...
2565  72904  20220611
2566  71647  20220611
2567  71650  20220611
2568  71800  20220611
2569  72117  20220611

[2570 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             64  9616900721790091   11  20220611160044   0.0    80     8
1             65                 0   11  20220611160047   0.0    80     8
2             66  9616900720048221   11  20220611160142   0.0    80     8
3             67  9616900722144595   11  20220611160252   0.0    80     8
4             68  9616900721599955   11  20220611160525   0.0    80     8
...          ...               ...  ...             ...   ...   ...   ...
2889       46418  9616900721923271    6  20220611162855   1.0   710    71
2890       46531  9616900722254954    6  20220611161937   1.0   380    38
2891       46640  9616900722198196    6  20220611161139   0.5  3130   313
2892       46641  9616900720343552    6  20220611161146   0.5  3130   313
2893       46642  9616900720410124   11  20220611162407   0.0  3130   313

         时间        日期
0     80044  20220611
1     80047  20220611
2     80142  20220611
3     80252  20220611
4     80525  20220611
...     ...       ...
2889  82855  20220611
2890  81937  20220611
2891  81139  20220611
2892  81146  20220611
2893  82407  20220611

[2894 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0            115  9616900722011552   11  20220611171552   0.0  1020   102
1            125  9616900721789980   11  20220611172151   0.0    80     8
2            126  9616900722048741   11  20220611172432   0.0    80     8
3            127  9616900720244045  101  20220611172617   1.6    80     8
4            128  9616900716202474  101  20220611172733   1.6    80     8
...          ...               ...  ...             ...   ...   ...   ...
2542       46532  9616900721663640   11  20220611171259   0.0   380    38
2543       46533                 0   11  20220611171304   0.0   380    38
2544       46645  9616900720361779   11  20220611170248   0.0  3130   313
2545       46646  9616900720343552    6  20220611172005   0.5  3130   313
2546       46647  9616900722198196    6  20220611172007   0.5  3130   313

         时间        日期
0     91552  20220611
1     92151  20220611
2     92432  20220611
3     92617  20220611
4     92733  20220611
...     ...       ...
2542  91259  20220611
2543  91304  20220611
2544  90248  20220611
2545  92005  20220611
2546  92007  20220611

[2547 rows x 9 columns]

oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             25                 0   11  20220611180001   0.0   380    38
1             26  9616900722005833   11  20220611181705   0.0   380    38
2             48  9616900730054972  101  20220611180151   2.4  6120   612
3            160  9616900720195975   11  20220611182816   0.0  1020   102
4            268  9616900721797212    6  20220611180410   1.0   160    16
...          ...               ...  ...             ...   ...   ...   ...
1910       46502  9616900722011776   11  20220611180550   0.0   780    78
1911       46503  9616900760030932  101  20220611180553   0.0   780    78
1912       46504  9616900722124671  101  20220611180558   0.0   780    78
1913       46534  9616900722024710   11  20220611182931   0.0   380    38
1914       46535  9616900721600966   11  20220611182935   0.0   380    38

          时间        日期
0     100001  20220611
1     101705  20220611
2     100151  20220611
3     102816  20220611
4     100410  20220611
...      ...       ...
1910  100550  20220611
1911  100553  20220611
1912  100558  20220611
1913  102931  20220611
1914  102935  20220611

[1915 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             27  9616900721571742   11  20220611192723   0.0   380    38
1            163  9616900722246419    6  20220611190059   0.0  1020   102
2            174  9616900722024201   11  20220611190404   0.0    80     8
3            175                 0   11  20220611190406   0.0    80     8
4            201                 0   11  20220611190032   0.0   860    86
...          ...               ...  ...             ...   ...   ...   ...
1240       46378  9616900730065082  101  20220611191510   1.6   880    88
1241       46379                 0  101  20220611190317   1.6   500    50
1242       46425  9616900722103683  101  20220611191905   1.6   880    88
1243       46577  9616900720362640   11  20220611192702   0.0  3100   310
1244       46648  9616900722084039  101  20220611192111   0.8  3130   313

          时间        日期
0     112723  20220611
1     110059  20220611
2     110404  20220611
3     110406  20220611
4     110032  20220611
...      ...       ...
1240  111510  20220611
1241  110317  20220611
1242  111905  20220611
1243  112702  20220611
1244  112111  20220611

[1245 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             3  9616900721987090  101  20220611201457   1.6   160    16
1           176                 0  101  20220611200550   0.0    80     8
2           177  9616900721707741    6  20220611201749   1.0    80     8
3           178  9616900721960767   11  20220611202022   0.0    80     8
4           179  9616900720250210  101  20220611202024   0.0    80     8
..          ...               ...  ...             ...   ...   ...   ...
967       46508                 0  101  20220611202528   1.6   780    78
968       46509  9616900722229637    6  20220611202715   1.0   780    78
969       46548  9616900711201098  101  20220611201513   1.6   300    30
970       46549  9616900721597650    6  20220611202743   1.0   300    30
971       46652  9616900730090690  101  20220611201132   1.6  2030   203

         时间        日期
0    121457  20220611
1    120550  20220611
2    121749  20220611
3    122022  20220611
4    122024  20220611
..      ...       ...
967  122528  20220611
968  122715  20220611
969  121513  20220611
970  122743  20220611
971  121132  20220611

[972 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0              5  9616900722171431  101  20220611210107   1.6   160    16
1             49  9616900730032930   10  20220611212045   0.0  6120   612
2            164  9616900721664607    6  20220611211249   1.0  1020   102
3            277  9616900722022079  101  20220611210727   0.0   160    16
4            278  9616900722265469  101  20220611212314   1.6   160    16
...          ...               ...  ...             ...   ...   ...   ...
1250       46515  9616900721565719  101  20220611212053   0.0   780    78
1251       46516  9616900720087122  101  20220611212055   0.0   780    78
1252       46517                 0   11  20220611212101   0.0   780    78
1253       46518  9616900720375920  101  20220611212105   0.0   780    78
1254       46519  9616900722236497    6  20220611212656   0.0   780    78

          时间        日期
0     130107  20220611
1     132045  20220611
2     131249  20220611
3     130727  20220611
4     132314  20220611
...      ...       ...
1250  132053  20220611
1251  132055  20220611
1252  132101  20220611
1253  132105  20220611
1254  132656  20220611

[1255 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0              8  9616900722265469  101  20220611221758   1.6   160    16
1             51  9616900730071587   11  20220611221441   0.0  6120   612
2             52                 0  101  20220611221445   2.4  6120   612
3            184  9616900721614619    6  20220611220719   1.0    80     8
4            185                 0   11  20220611221240   0.0    80     8
...          ...               ...  ...             ...   ...   ...   ...
1347       46107  9616900721950045    4  20220611220756   0.0   170    17
1348       46108  9616900721946149  101  20220611220939   1.6   170    17
1349       46109                 0  101  20220611221132   1.6   170    17
1350       46578  9616900722252291    6  20220611222558   1.0   880    88
1351       46655  9616900730052023    6  20220611222321   0.0  2030   203

          时间        日期
0     141758  20220611
1     141441  20220611
2     141445  20220611
3     140719  20220611
4     141240  20220611
...      ...       ...
1347  140756  20220611
1348  140939  20220611
1349  141132  20220611
1350  142558  20220611
1351  142321  20220611

[1352 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             34  9616900722254954    6  20220611232834   1.0   380    38
1            290                 0  101  20220611231830   1.6  1070   107
2            291  9616900720291418  101  20220611231835   1.6  1070   107
3            330  9616900720389154  101  20220611231350   1.6   160    16
4            380  9616900722236228    6  20220611231043   1.0   770    77
...          ...               ...  ...             ...   ...   ...   ...
1490       46260  9616900721942837    6  20220611231617   1.0  2800   280
1491       46477                 0   11  20220611230839   0.0   710    71
1492       46478  9616900720234853   10  20220611232023   0.0   710    71
1493       46589  9616900722059072  101  20220611232215   1.6   880    88
1494       46590  9616900722059072  101  20220611232218   1.6   880    88

          时间        日期
0     152834  20220611
1     151830  20220611
2     151835  20220611
3     151350  20220611
4     151043  20220611
...      ...       ...
1490  151617  20220611
1491  150839  20220611
1492  152023  20220611
1493  152215  20220611
1494  152218  20220611

[1495 rows x 9 columns]

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,50000,0,0,0
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611,50000,0,0,0
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611,50000,0,0,0
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611,50000,0,0,0
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611,50000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611,150000,0,0,0
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611,150000,0,0,0
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611,150000,6,3,9
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611,150000,8,3,11
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,150000,4,0,4

In [71]:
ALLIDSY3=ALLIDSY
##以30分钟为粒度统计老年卡和其他卡
##在此基础上新建统计框
IDSY['段开始时间']=0
IDSY['老年卡客运量']=0
IDSY['其他卡客运量']=0
IDSY['总客运量']=0
for i in range(0,8):
    t1=920000+i*10000
    t2=920000+i*10000+3000
    t3=40000+(i+12)*10000
    #t2=i*100000+6000
    ##筛选时间段内的所有刷卡数据
    listt=[]   
    for g in range(0,len(oldcard1)):
        TIME=int(oldcard1['时间'].iloc[g])
        if TIME>=t1 and TIME<=t2:
            listt.append(g)
    oldcard2=oldcard1.loc[listt,:]
    oldcard2.reset_index(drop=True,inplace=True) 
    print('oldcard2')
    print(oldcard2)
    IDSY['段开始时间']=0
    IDSY['老年卡客运量']=0
    IDSY['其他卡客运量']=0
    IDSY['总客运量']=0
    ##按照线路名统计每条线上的刷卡数据
    for i in range(0,len(IDSY)):

        IDSY['段开始时间'].iloc[i]=t3
        tsum=0
        list2=[]
        for k in range(0,len(oldcard2)):
            id1=oldcard2['线路编号'].iloc[k]
            id2=IDSY['线路编号'].iloc[i] 
            if id1==id2:                  
                tsum = tsum+1
                IDSY['总客运量'].iloc[i]=tsum
                list2.append(k)
        oldcard3=oldcard2.loc[list2,:]
        #print('oldcard3')
        #print(oldcard3)
        ##线路相同的情况下的刷卡类型统计
        oldcard4=oldcard3[(oldcard3['卡类型']==6)|(oldcard3['卡类型']==11)]
        #print('oldcard4')
        #print(oldcard4)
        osum=len(oldcard4)
        IDSY['老年卡客运量'].iloc[i]=osum
        fosum=tsum-osum
        IDSY['其他卡客运量'].iloc[i]=fosum
    ALLIDSY3=ALLIDSY3.append(IDSY)      
ALLIDSY3

oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             14  9616900721576893  101  20220612000159   1.6   160    16
1             53  9616900730127920    6  20220612000641   0.0  6120   612
2             54  9616900730046951    6  20220612001724   0.0  6120   612
3            267  9616900722259800    6  20220612002048   0.0  1010   101
4            331  9616900720235844   10  20220612002247   0.0   160    16
...          ...               ...  ...             ...   ...   ...   ...
1814       46593  9616900722124520    6  20220612000135   1.0   880    88
1815       46594  9616900730031468   10  20220612000626   0.0   880    88
1816       46595                 0   10  20220612001441   0.0   880    88
1817       46596  9616900721610966  101  20220612002507   0.0   880    88
1818       46657  9616900730068322   11  20220612002208   0.0  2030   203

          时间        日期
0     920159  20220611
1     920641  20220611
2     921724  20220611
3     922048  20220611
4     922247  20220611
...      ...       ...
1814  920135  20220611
1815  920626  20220611
1816  921441  20220611
1817  922507  20220611
1818  922208  20220611

[1819 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             17                 0   11  20220612010128   0.0   160    16
1             18  9616900720346037   11  20220612010131   0.0   160    16
2             39  9616900722014615    6  20220612010440   1.0   380    38
3             40  9616900721606917    6  20220612010711   1.0   380    38
4             57  9616900722246189    6  20220612010514   1.0   160    16
...          ...               ...  ...             ...   ...   ...   ...
1799       46576  9616900722191396   11  20220612012039   0.0   780    78
1800       46650  9616900721785296    6  20220612012343   0.5  3130   313
1801       46659  9616900730005839  101  20220612011315   1.6  2030   203
1802       46660  9616900760079201  101  20220612012840   1.6   270    27
1803       46661  9616900721700617    2  20220612012844   1.6   270    27

          时间        日期
0     930128  20220611
1     930131  20220611
2     930440  20220611
3     930711  20220611
4     930514  20220611
...      ...       ...
1799  932039  20220611
1800  932343  20220611
1801  931315  20220611
1802  932840  20220611
1803  932844  20220611

[1804 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0            213  9616900722253028    6  20220612020410   0.0  1020   102
1            214  9616900760015070  101  20220612020437   0.0  1020   102
2            215  9616900722137548   11  20220612021531   0.0  1020   102
3            242  9616900721611269    6  20220612020222   1.0    80     8
4            312  9616900720407086  101  20220612020954   1.6  1010   101
...          ...               ...  ...             ...   ...   ...   ...
1095       46632  9616900722101757  101  20220612021605   0.0   200    20
1096       46633  9616900722042824  101  20220612021658   1.6   200    20
1097       46634  9616900722023321    4  20220612021701   0.0   200    20
1098       46666  9616900722246864    6  20220612020146   0.0   270    27
1099       46667  9616900721772135    6  20220612020151   0.0   270    27

          时间        日期
0     940410  20220611
1     940437  20220611
2     941531  20220611
3     940222  20220611
4     940954  20220611
...      ...       ...
1095  941605  20220611
1096  941658  20220611
1097  941701  20220611
1098  940146  20220611
1099  940151  20220611

[1100 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0           352  9616900722209986    6  20220612030029   0.0  700    70
1           353  9616900722145517   11  20220612030411   0.0  700    70
2           354  9616900721592175  101  20220612030421   0.0  700    70
3           782  9616900716054745  101  20220612030342   1.6  180    18
4           783                 0  101  20220612030343   1.6  180    18
..          ...               ...  ...             ...   ...  ...   ...
362       46178  9616900721779136  101  20220612030621   0.0  170    17
363       46278  9616900730051360    6  20220612032033   0.0  991    99
364       46279  9616900711050160  101  20220612032044   1.6  991    99
365       46280  9616900730055505  101  20220612032813   0.0  991    99
366       46613                 0  101  20220612032902   1.6  881    88

         时间        日期
0    950029  20220611
1    950411  20220611
2    950421  20220611
3    950342  20220611
4    950343  20220611
..      ...       ...
362  950621  20220611
363  952033  20220611
364  952044  20220611
365  952813  20220611
366  952902  20220611

[367 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0           786  9616900720396384    6  20220612040905   1.0  180    18
1          1551  9616900720090870  101  20220612040110   1.6  551    55
2          1552  9616900711196957  101  20220612040240   1.6  551    55
3          1553  9616900721999584  101  20220612042358   1.6  551    55
4          1554  9616900721999584  101  20220612042359   1.6  551    55
..          ...               ...  ...             ...   ...  ...   ...
233       46199  9616900720409828   11  20220612040024   0.0   11     1
234       46200  9616900720409829   11  20220612040027   0.0   11     1
235       46438  9616900721610658   11  20220612042025   0.0  881    88
236       46439  9616900720307595    6  20220612042247   1.0  881    88
237       46619                 0   11  20220612042057   0.0  881    88

         时间        日期
0    960905  20220611
1    960110  20220611
2    960240  20220611
3    962358  20220611
4    962359  20220611
..      ...       ...
233  960024  20220611
234  960027  20220611
235  962025  20220611
236  962247  20220611
237  962057  20220611

[238 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0           209  9616900720232236    6  20220612052333   1.0  281    28
1           210  9616900722207946    6  20220612052500   1.0  281    28
2           249  9616900760084545  101  20220612052504   1.6  281    28
3          1555  9616900720197181  101  20220612050926   0.0  551    55
4          1556  9616900720197183  101  20220612050931   0.0  551    55
..          ...               ...  ...             ...   ...  ...   ...
221       46622  9616900720362410    2  20220612051700   1.6  881    88
222       46623  9616900720362410    2  20220612051705   1.6  881    88
223       46624  9616900721511104    6  20220612051710   1.0  881    88
224       46625  9616900720121233  101  20220612052838   1.6  881    88
225       46626  9616900720135989  101  20220612052844   1.6  881    88

         时间        日期
0    972333  20220611
1    972500  20220611
2    972504  20220611
3    970926  20220611
4    970931  20220611
..      ...       ...
221  971700  20220611
222  971705  20220611
223  971710  20220611
224  972838  20220611
225  972844  20220611

[226 rows x 9 columns]
oldcard2
    Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0         1617  9616900101114963  101  20220612061547   1.6  551    55
1         1618  9616900101114963  101  20220612061548   1.6  551    55
2         3765  9616900721638533  101  20220612060037   1.6  880    88
3         3766  9616900722005258  101  20220612060056   1.6  880    88
4         3767  9616900721646047    2  20220612060102   1.6  880    88
5         3768  9616900721688415  101  20220612060104   1.6  880    88
6         7047  9616900721949953    4  20220612061337   1.0  260    26
7        21404  9616900722011730   11  20220612061601   0.0  180    18
8        24177  9616900722052831  101  20220612060151   1.6  880    88
9        25237                 0  101  20220612060754   1.6  661    66
10       25259  9616900722227009    6  20220612062146   1.0  661    66
11       27033  9616900721921662    6  20220612061131   1.0  551    55
12       27034  9616900720334334  101  20220612061134   1.6  551    55
13       27133  9616900720319792  101  20220612060856   1.6  201    20
14       28422  9616900720234694   10  20220612060227   0.0  201    20
15       30231  9616900720110302  101  20220612061700   1.6  200    20
16       31621  9616900721712317   11  20220612060655   0.0  991    99
17       31789  9616900721751600  101  20220612060259   1.6  260    26
18       31999  9616900721751600  101  20220612060301   1.6  260    26
19       33506  9616900760055375  101  20220612061424   1.6  201    20
20       35241  9616900720136737  101  20220612060232   1.6   50     5
21       36491                 0  101  20220612061434   1.6   50     5
22       45184                 0  101  20220612060013   0.0  661    66
23       45855                 0   10  20220612060843   0.0  291    29

        时间        日期
0   981547  20220611
1   981548  20220611
2   980037  20220611
3   980056  20220611
4   980102  20220611
5   980104  20220611
6   981337  20220611
7   981601  20220611
8   980151  20220611
9   980754  20220611
10  982146  20220611
11  981131  20220611
12  981134  20220611
13  980856  20220611
14  980227  20220611
15  981700  20220611
16  980655  20220611
17  980259  20220611
18  980301  20220611
19  981424  20220611
20  980232  20220611
21  981434  20220611
22  980013  20220611
23  980843  20220611

oldcard2
Empty DataFrame
Columns: [Unnamed: 0, 卡号, 卡类型, 交易时间需减去8小时, 交易金额, 线路号, 线路编号, 时间, 日期]
Index: []

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,50000,0,0,0
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611,50000,0,0,0
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611,50000,0,0,0
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611,50000,0,0,0
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611,50000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611,230000,0,0,0
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611,230000,0,0,0
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611,230000,0,0,0
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611,230000,0,0,0
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,230000,0,0,0

In [72]:
##以30分钟为粒度统计老年卡和其他卡
##在此基础上新建统计框
IDSY['段开始时间']=None
IDSY['老年卡客运量']=0
IDSY['其他卡客运量']=0
IDSY['总客运量']=0
#t1=40000+0*10000
t1=40000+0*10000+3000
t2=40000+0*10000+6000
#筛选时间段内的所有刷卡数据
listt=[]   
for g in range(0,len(oldcard1)):
    TIME=int(oldcard1['时间'].iloc[g])
    if TIME>=t1 and TIME<=t2:
        listt.append(g)
oldcard2=oldcard1.loc[listt,:]
oldcard2.reset_index(drop=True,inplace=True) 
print('oldcard2')
print(oldcard2)
##按照线路名统计每条线上的刷卡数据
for i in range(0,len(IDSY)):
    IDSY['段开始时间'].iloc[i]=t1
    tsum=0
    list2=[]
    for k in range(0,len(oldcard2)):
        id1=oldcard2['线路编号'].iloc[k]
        id2=IDSY['线路编号'].iloc[i] 
        if id1==id2:                  
            tsum = tsum+1
            IDSY['总客运量'].iloc[i]=tsum
            list2.append(k)
    oldcard3=oldcard2.loc[list2,:]
    #print('oldcard3')
    #print(oldcard3)
    ##线路相同的情况下的刷卡类型统计
    oldcard4=oldcard3[(oldcard3['卡类型']==6)|(oldcard3['卡类型']==11)]
    #print('oldcard4')
    #print(oldcard4)
    osum=len(oldcard4)
    IDSY['老年卡客运量'].iloc[i]=osum
    fosum=tsum-osum
    IDSY['其他卡客运量'].iloc[i]=fosum
ALLIDSY2=IDSY       
ALLIDSY2

oldcard2
   Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号     时间  \
0        1162  9616900730121574    6  20220611124737   1.5  6220   622  44737

         日期
0  20220611

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,43000,0,0,0
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611,43000,0,0,0
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611,43000,0,0,0
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611,43000,0,0,0
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611,43000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611,43000,0,0,0
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611,43000,0,0,0
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611,43000,0,0,0
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611,43000,1,0,1
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,43000,0,0,0

In [73]:
##以30分钟为粒度统计老年卡和其他卡
##在此基础上新建统计框
for i in range(1,12):
    t1=40000+i*10000+3000
    t2=40000+i*10000+6000
    #t2=i*100000+6000
    ##筛选时间段内的所有刷卡数据
    listt=[]   
    for g in range(0,len(oldcard1)):
        TIME=int(oldcard1['时间'].iloc[g])
        if TIME>=t1 and TIME<=t2:
            listt.append(g)
    oldcard2=oldcard1.loc[listt,:]
    oldcard2.reset_index(drop=True,inplace=True) 
    print('oldcard2')
    print(oldcard2)
    ##按照线路名统计每条线上的刷卡数据
    IDSY['段开始时间']=0
    IDSY['老年卡客运量']=0
    IDSY['其他卡客运量']=0
    IDSY['总客运量']=0
    for i in range(0,len(IDSY)):

        IDSY['段开始时间'].iloc[i]=t1
        tsum=0
        list2=[]
        for k in range(0,len(oldcard2)):
            id1=oldcard2['线路编号'].iloc[k]
            id2=IDSY['线路编号'].iloc[i] 
            if id1==id2:                  
                tsum = tsum+1
                IDSY['总客运量'].iloc[i]=tsum
                list2.append(k)
        oldcard3=oldcard2.loc[list2,:]
        #print('oldcard3')
        #print(oldcard3)
        ##线路相同的情况下的刷卡类型统计
        oldcard4=oldcard3[(oldcard3['卡类型']==6)|(oldcard3['卡类型']==11)]
      ##  print('oldcard4')
        #print(oldcard4)
        osum=len(oldcard4)
        IDSY['老年卡客运量'].iloc[i]=osum
        fosum=tsum-osum
        IDSY['其他卡客运量'].iloc[i]=fosum
    ALLIDSY2=ALLIDSY2.append(IDSY)      
ALLIDSY2

oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0          1164  9616900722002852   11  20220611133526   0.0  6220   622
1          1165  9616900730049706    6  20220611133537   1.5  6220   622
2          1569  9616900721765570    6  20220611134939   1.0  2320   232
3          1570  9616900730013087    6  20220611135412   1.0  2320   232
4          1571  9616900730046950    6  20220611135416   1.0  2320   232
..          ...               ...  ...             ...   ...   ...   ...
277       45469  9616900721558271  101  20220611135924   2.4  6120   612
278       45871  9616900722140035   11  20220611135059   0.0   870    87
279       46386  9616900721960321   11  20220611134902   0.0   780    78
280       46387  9616900720111694  101  20220611134906   1.6   780    78
281       46388  9616900720039562  101  20220611134957   1.6   780    78

        时间        日期
0    53526  20220611
1    53537  20220611
2    54939  20220611
3    55412  20220611
4    55416  20220611
..     ...       ...
277  55924  20220611
278  55059  20220611
279  54902  20220611
280  54906  20220611
281  54957  20220611

[282 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             86  9616900720185325   11  20220611143146   0.0   860    86
1             87  9616900721525899    6  20220611143436   1.0   860    86
2             88  9616900722231422    6  20220611143633   1.0   860    86
3             89  9616900722197472    6  20220611143914   1.0   860    86
4             90  9616900730090315  101  20220611144108   1.6   860    86
...          ...               ...  ...             ...   ...   ...   ...
2294       46351  9616900730061680   11  20220611145446   0.0  2030   203
2295       46390  9616900720409463   11  20220611143304   0.0   780    78
2296       46391  9616900722229237    6  20220611145621   0.0   780    78
2297       46392  9616900722206131    6  20220611145623   0.0   780    78
2298       46393  9616900720177542    6  20220611145629   0.0   780    78

         时间        日期
0     63146  20220611
1     63436  20220611
2     63633  20220611
3     63914  20220611
4     64108  20220611
...     ...       ...
2294  65446  20220611
2295  63304  20220611
2296  65621  20220611
2297  65623  20220611
2298  65629  20220611

[2299 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             46  9616900721755184  101  20220611153152   2.4  6120   612
1             59  9616900720189007   11  20220611155403   0.0    80     8
2             60                 0   10  20220611155408   0.0    80     8
3             61                 0   11  20220611155541   0.0    80     8
4             62  9616900716231948  101  20220611155815   1.6    80     8
...          ...               ...  ...             ...   ...   ...   ...
2803       46451  9616900722273262    4  20220611153713   1.0   780    78
2804       46452  9616900721723158   11  20220611155229   0.0   780    78
2805       46453  9616900720179588   11  20220611155230   0.0   780    78
2806       46482  9616900721585528   11  20220611155323   0.0   300    30
2807       46530  9616900722016402    6  20220611153233   0.0   380    38

         时间        日期
0     73152  20220611
1     75403  20220611
2     75408  20220611
3     75541  20220611
4     75815  20220611
...     ...       ...
2803  73713  20220611
2804  75229  20220611
2805  75230  20220611
2806  75323  20220611
2807  73233  20220611

[2808 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             19  9616900100755824  101  20220611164156   1.6   380    38
1            103  9616900720344056    6  20220611165427   0.5  3360   336
2            114  9616900721938848   11  20220611163222   0.0  1020   102
3            124  9616900721922070    6  20220611164056   1.0    80     8
4            225  9616900722193959  101  20220611163129   0.0   160    16
...          ...               ...  ...             ...   ...   ...   ...
2667       46455  9616900721718088    6  20220611165452   1.0   780    78
2668       46456  9616900722024540   11  20220611165633   0.0   780    78
2669       46457  9616900721763598  101  20220611165642   1.6   780    78
2670       46643  9616900720343245    6  20220611163717   0.5  3130   313
2671       46644  9616900721785296    6  20220611165558   0.5  3130   313

         时间        日期
0     84156  20220611
1     85427  20220611
2     83222  20220611
3     84056  20220611
4     83129  20220611
...     ...       ...
2667  85452  20220611
2668  85633  20220611
2669  85642  20220611
2670  83717  20220611
2671  85558  20220611

[2672 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0             20  9616900721951440    4  20220611175622   1.0  380    38
1             21  9616900720034094  101  20220611175626   1.6  380    38
2             22  9616900722020592    6  20220611175750   0.0  380    38
3             23  9616900721793242    6  20220611175754   0.0  380    38
4             24                 0   11  20220611175757   0.0  380    38
...          ...               ...  ...             ...   ...  ...   ...
2333       46462  9616900720308685  101  20220611175751   0.0  780    78
2334       46463  9616900721713414   11  20220611174405   0.0  710    71
2335       46496  9616900714005742  101  20220611173604   1.6  300    30
2336       46497  9616900714005742  101  20220611173606   1.6  300    30
2337       46498  9616900721942881    6  20220611173936   1.0  300    30

         时间        日期
0     95622  20220611
1     95626  20220611
2     95750  20220611
3     95754  20220611
4     95757  20220611
...     ...       ...
2333  95751  20220611
2334  94405  20220611
2335  93604  20220611
2336  93606  20220611
2337  93936  20220611

[2338 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0              0  9616900720343197    6  20220611184643   1.0  160    16
1              1  9616900720229892    6  20220611184819   1.0  160    16
2              2  9616900722020003    6  20220611184837   1.0  160    16
3            133  9616900722262776  101  20220611185246   0.0   80     8
4            134  9616900721575341   11  20220611185528   0.0   80     8
...          ...               ...  ...             ...   ...  ...   ...
1589       46543  9616900721708108    6  20220611184254   1.0  300    30
1590       46544  9616900720331714  101  20220611184358   1.6  300    30
1591       46545  9616900722091067   11  20220611185348   0.0  300    30
1592       46546  9616900720409160   11  20220611185355   0.0  300    30
1593       46547  9616900760110209  101  20220611185910   1.6  300    30

          时间        日期
0     104643  20220611
1     104819  20220611
2     104837  20220611
3     105246  20220611
4     105528  20220611
...      ...       ...
1589  104254  20220611
1590  104358  20220611
1591  105348  20220611
1592  105355  20220611
1593  105910  20220611

[1594 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             28  9616900721764655    6  20220611193847   1.0   380    38
1            275                 0  101  20220611194622   1.6   160    16
2            417  9616900722103683  101  20220611194610   0.0   350    35
3            418  9616900720082119   11  20220611194826   0.0   350    35
4            494  9616900721526471    6  20220611195458   1.0   700    70
...          ...               ...  ...             ...   ...   ...   ...
1031       46254  9616900730032428   10  20220611194314   0.0  2800   280
1032       46255  9616900730121799    6  20220611195726   1.0  2800   280
1033       46426  9616900722206866    6  20220611194107   1.0   880    88
1034       46467  9616900720228904    6  20220611193556   1.0   710    71
1035       46468  9616900722199307   11  20220611195229   0.0   710    71

          时间        日期
0     113847  20220611
1     114622  20220611
2     114610  20220611
3     114826  20220611
4     115458  20220611
...      ...       ...
1031  114314  20220611
1032  115726  20220611
1033  114107  20220611
1034  113556  20220611
1035  115229  20220611

[1036 rows x 9 columns]

oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0              4  9616900711049089  101  20220611203704   0.0  160    16
1            181  9616900721950503    4  20220611203216   1.0   80     8
2            182  9616900721653575  101  20220611203227   1.6   80     8
3            183  9616900721543529  101  20220611203554   1.6   80     8
4            378  9616900720327187  101  20220611205705   1.6  770    77
...          ...               ...  ...             ...   ...  ...   ...
1149       46511  9616900721511441  101  20220611204426   1.6  780    78
1150       46536                 0   11  20220611203539   0.0  380    38
1151       46537  9616900720405411    6  20220611203543   1.0  380    38
1152       46538  9616900722041912   11  20220611203546   0.0  380    38
1153       46550  9616900721791468  101  20220611203256   0.0  300    30

          时间        日期
0     123704  20220611
1     123216  20220611
2     123227  20220611
3     123554  20220611
4     125705  20220611
...      ...       ...
1149  124426  20220611
1150  123539  20220611
1151  123543  20220611
1152  123546  20220611
1153  123256  20220611

[1154 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0              6                 0  101  20220611214829   0.0   160    16
1              7  9616900722209314  101  20220611215210   1.6   160    16
2             29  9616900721540431    6  20220611213252   1.0   380    38
3             30  9616900720405319    6  20220611213254   1.0   380    38
4             31  9616900722090180   11  20220611214609   0.0   380    38
...          ...               ...  ...             ...   ...   ...   ...
1443       46560                 0   11  20220611215246   0.0   780    78
1444       46561  9616900720408594   11  20220611215250   0.0   780    78
1445       46649  9616900722084039  101  20220611213543   0.8  3130   313
1446       46653  9616900730007762   11  20220611213526   0.0  2030   203
1447       46654  9616900730010286   11  20220611213757   0.0  2030   203

          时间        日期
0     134829  20220611
1     135210  20220611
2     133252  20220611
3     133254  20220611
4     134609  20220611
...      ...       ...
1443  135246  20220611
1444  135250  20220611
1445  133543  20220611
1446  133526  20220611
1447  133757  20220611

[1448 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0            165  9616900721516242   11  20220611223425   0.0  1020   102
1            166  9616900721643254   11  20220611223912   0.0  1020   102
2            167  9616900722239381    6  20220611224741   1.0  1020   102
3            168                 0   11  20220611225347   0.0  1020   102
4            289  9616900716092607  101  20220611225053   1.6  1070   107
...          ...               ...  ...             ...   ...   ...   ...
1351       46585  9616900716308633  101  20220611224229   0.0   880    88
1352       46586  9616900720090195  101  20220611224322   1.6   880    88
1353       46587  9616900722199212   11  20220611225118   0.0   880    88
1354       46588  9616900721672328  101  20220611225448   1.6   880    88
1355       46656  9616900730062554    6  20220611223302   1.0  2030   203

          时间        日期
0     143425  20220611
1     143912  20220611
2     144741  20220611
3     145347  20220611
4     145053  20220611
...      ...       ...
1351  144229  20220611
1352  144322  20220611
1353  145118  20220611
1354  145448  20220611
1355  143302  20220611

[1356 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0              9  9616900720090793  101  20220611235304   1.6   160    16
1             10  9616900711134971  101  20220611235320   1.6   160    16
2             11  9616900720311811   10  20220611235705   0.0   160    16
3             12                 0  101  20220611235714   1.6   160    16
4             13  9616900716121676  101  20220611235715   1.6   160    16
...          ...               ...  ...             ...   ...   ...   ...
1754       46402  9616900722019893    6  20220611234249   0.5  3370   337
1755       46403  9616900722137049   11  20220611234258   0.0  3370   337
1756       46404                 0   11  20220611234606   0.0  3370   337
1757       46562  9616900721610966  101  20220611235615   1.6   780    78
1758       46591  9616900720190925   11  20220611235936   0.0   880    88

          时间        日期
0     155304  20220611
1     155320  20220611
2     155705  20220611
3     155714  20220611
4     155715  20220611
...      ...       ...
1754  154249  20220611
1755  154258  20220611
1756  154606  20220611
1757  155615  20220611
1758  155936  20220611

[1759 rows x 9 columns]

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,53000,0,0,0
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611,53000,0,0,0
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611,53000,0,0,0
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611,53000,0,0,0
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611,53000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611,153000,0,0,0
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611,153000,0,0,0
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611,153000,1,1,2
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611,153000,3,1,4
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,153000,1,3,4

In [74]:
ALLIDSY4=ALLIDSY2
##以30分钟为粒度统计老年卡和其他卡
##在此基础上新建统计框
IDSY['段开始时间']=0
IDSY['老年卡客运量']=0
IDSY['其他卡客运量']=0
IDSY['总客运量']=0
for i in range(0,8):
    t1=920000+i*10000+3000
    t2=920000+i*10000+6000
    t3=40000+(i+12)*10000+3000
    #t2=i*100000+6000
    ##筛选时间段内的所有刷卡数据
    listt=[]   
    for g in range(0,len(oldcard1)):
        TIME=int(oldcard1['时间'].iloc[g])
        if TIME>=t1 and TIME<=t2:
            listt.append(g)
    oldcard2=oldcard1.loc[listt,:]
    oldcard2.reset_index(drop=True,inplace=True) 
    print('oldcard2')
    print(oldcard2)
    ##按照线路名统计每条线上的刷卡数据
    IDSY['段开始时间']=0
    IDSY['老年卡客运量']=0
    IDSY['其他卡客运量']=0
    IDSY['总客运量']=0
    for i in range(0,len(IDSY)):

        IDSY['段开始时间'].iloc[i]=t3
        tsum=0
        list2=[]
        for k in range(0,len(oldcard2)):
            id1=oldcard2['线路编号'].iloc[k]
            id2=IDSY['线路编号'].iloc[i] 
            if id1==id2:                  
                tsum = tsum+1
                IDSY['总客运量'].iloc[i]=tsum
                list2.append(k)
        oldcard3=oldcard2.loc[list2,:]
        #print('oldcard3')
        #print(oldcard3)
        ##线路相同的情况下的刷卡类型统计
        oldcard4=oldcard3[(oldcard3['卡类型']==6)|(oldcard3['卡类型']==11)]
        #print('oldcard4')
        #print(oldcard4)
        osum=len(oldcard4)
        IDSY['老年卡客运量'].iloc[i]=osum
        fosum=tsum-osum
        IDSY['其他卡客运量'].iloc[i]=fosum
    ALLIDSY4=ALLIDSY4.append(IDSY)      
ALLIDSY4

oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             15  9616900716032936  101  20220612005020   0.0   160    16
1             16  9616900720164833  101  20220612005027   0.0   160    16
2             38                 0   11  20220612003923   0.0   380    38
3            292  9616900721707883    6  20220612003559   1.0  1070   107
4            293  9616900720228852    6  20220612004148   1.0  1070   107
...          ...               ...  ...             ...   ...   ...   ...
1776       46601                 0   11  20220612005909   0.0   880    88
1777       46602  9616900722002992   11  20220612005913   0.0   880    88
1778       46603  9616900720047521   11  20220612005920   0.0   880    88
1779       46604  9616900721722634   11  20220612005924   0.0   880    88
1780       46658  9616900721774419    6  20220612003001   1.0  2030   203

          时间        日期
0     925020  20220611
1     925027  20220611
2     923923  20220611
3     923559  20220611
4     924148  20220611
...      ...       ...
1776  925909  20220611
1777  925913  20220611
1778  925920  20220611
1779  925924  20220611
1780  923001  20220611

[1781 rows x 9 columns]
oldcard2
      Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0             41  9616900721786300  101  20220612015555   1.6   380    38
1            212  9616900721776445  101  20220612013249   0.0  1020   102
2            236  9616900721772118    6  20220612013131   1.0    80     8
3            237  9616900711174715  101  20220612013133   1.6    80     8
4            238  9616900721700101    6  20220612013226   1.0    80     8
...          ...               ...  ...             ...   ...   ...   ...
1597       46651  9616900721585747   11  20220612015005   0.0  3130   313
1598       46662  9616900722019676    6  20220612013419   1.0   270    27
1599       46663  9616900722268015  101  20220612014737   1.6   270    27
1600       46664  9616900722196402  101  20220612015350   1.6   270    27
1601       46665  9616900720382304  101  20220612015539   1.6   270    27

          时间        日期
0     935555  20220611
1     933249  20220611
2     933131  20220611
3     933133  20220611
4     933226  20220611
...      ...       ...
1597  935005  20220611
1598  933419  20220611
1599  934737  20220611
1600  935350  20220611
1601  935539  20220611

[1602 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0            42  9616900716096307  101  20220612023009   0.0   380    38
1           216  9616900720361737   11  20220612023341   0.0  1020   102
2           316  9616900722141104    6  20220612025216   1.0  1010   101
3           343  9616900722282021    4  20220612024113   1.0   160    16
4           351  9616900722279925   11  20220612023448   0.0   700    70
..          ...               ...  ...             ...   ...   ...   ...
613       46277  9616900722270421  101  20220612025742   1.6   991    99
614       46434  9616900721607073    6  20220612023930   1.0   881    88
615       46435  9616900730073099    6  20220612024338   1.0   881    88
616       46436  9616900721608031  101  20220612024956   0.0   881    88
617       46437  9616900720355294  101  20220612025111   0.0   881    88

         时间        日期
0    943009  20220611
1    943341  20220611
2    945216  20220611
3    944113  20220611
4    943448  20220611
..      ...       ...
613  945742  20220611
614  943930  20220611
615  944338  20220611
616  944956  20220611
617  945111  20220611

[618 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额   线路号  线路编号  \
0           206  9616900721951907   11  20220612034829   0.0   281    28
1          1181  9616900721800607   10  20220612033005   0.0   881    88
2          1182  9616900720059626  101  20220612033507   0.0   881    88
3          1970                 0  101  20220612035633   1.6  1051   105
4          1971                 0  101  20220612035634   1.6  1051   105
..          ...               ...  ...             ...   ...   ...   ...
302       46614  9616900100521853  101  20220612033639   1.6   881    88
303       46615  9616900720366968  101  20220612033645   1.6   881    88
304       46616  9616900720366968  101  20220612033649   1.6   881    88
305       46617  9616900722054974    6  20220612033739   1.0   881    88
306       46618  9616900760043924  101  20220612034750   1.6   881    88

         时间        日期
0    954829  20220611
1    953005  20220611
2    953507  20220611
3    955633  20220611
4    955634  20220611
..      ...       ...
302  953639  20220611
303  953645  20220611
304  953649  20220611
305  953739  20220611
306  954750  20220611

[307 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0           207  9616900722041095    4  20220612043237   1.0  281    28
1           208  9616900721615820  101  20220612043240   1.6  281    28
2          1183  9616900720234978   10  20220612043224   0.0  881    88
3          1184  9616900722211003    6  20220612043238   1.0  881    88
4          1185  9616900730063809    4  20220612043409   1.0  881    88
..          ...               ...  ...             ...   ...  ...   ...
313       46204                 0  101  20220612045219   0.0   11     1
314       46281  9616900730033757   10  20220612043705   0.0  991    99
315       46282  9616900730090946  101  20220612043929   1.6  991    99
316       46283  9616900739000834  101  20220612043932   1.6  991    99
317       46284  9616900721572679  101  20220612044522   1.6  991    99

         时间        日期
0    963237  20220611
1    963240  20220611
2    963224  20220611
3    963238  20220611
4    963409  20220611
..      ...       ...
313  965219  20220611
314  963705  20220611
315  963929  20220611
316  963932  20220611
317  964522  20220611

[318 rows x 9 columns]
oldcard2
     Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号  \
0          1513  9616900722260280    6  20220612053607   0.0  230    23
1          3486  9616900722158238  101  20220612053529   1.6  260    26
2          3487  9616900720235387   10  20220612053925   0.0  260    26
3          3488                 0   10  20220612053927   0.0  260    26
4          3764  9616900730075354  101  20220612055733   1.6  880    88
..          ...               ...  ...             ...   ...  ...   ...
96        44069  9616900721519292  101  20220612055543   1.6  230    23
97        44070  9616900721519292  101  20220612055544   1.6  230    23
98        46343  9616900720234694   10  20220612053535   0.0  991    99
99        46344                 0   10  20220612053538   0.0  991    99
100       46627  9616900721926397  101  20220612053944   1.6  881    88

         时间        日期
0    973607  20220611
1    973529  20220611
2    973925  20220611
3    973927  20220611
4    975733  20220611
..      ...       ...
96   975543  20220611
97   975544  20220611
98   973535  20220611
99   973538  20220611
100  973944  20220611

[101 rows x 9 columns]
oldcard2
   Unnamed: 0                卡号  卡类型      交易时间需减去8小时  交易金额  线路号  线路编号      时间  \
0        6748  9616900720319792  101  20220612063952   0.0  601    60  983952

         日期
0  20220611
oldcard2
Empty DataFrame
Columns: [Unnamed: 0, 卡号, 卡类型, 交易时间需减去8小时, 交易金额, 线路号, 线路编号, 时间, 日期]
Index: []

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,53000,0,0,0
1,2209,9616900720307617,6,20220611141041,1.0,20,2,61041,20220611,53000,0,0,0
2,9428,9616900722227198,6,20220611153036,0.0,30,3,73036,20220611,53000,0,0,0
3,1241,0,11,20220611142155,0.0,50,5,62155,20220611,53000,0,0,0
4,41758,0,11,20220611150926,0.0,60,6,70926,20220611,53000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,8173,9616900730130399,6,20220611162433,0.5,3850,385,82433,20220611,233000,0,0,0
160,4351,9616900730079653,11,20220611145849,0.0,3870,387,65849,20220611,233000,0,0,0
161,43,9616900730044189,11,20220611142552,0.0,6120,612,62552,20220611,233000,0,0,0
162,1162,9616900730121574,6,20220611124737,1.5,6220,622,44737,20220611,233000,0,0,0
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,233000,0,0,0

In [75]:
ALLIDSY3.to_csv(r'F:\扬州\NEWALLIDSY3_11.csv')
ALLIDSY4.to_csv(r'F:\扬州\NEWALLIDSY4_11.csv')

In [76]:
ALL=ALLIDSY3
ALL=ALL.append(ALLIDSY4)
ALL.sort_values(by='段开始时间')

,Unnamed: 0,卡号,卡类型,交易时间需减去8小时,交易金额,线路号,线路编号,时间,日期,段开始时间,老年卡客运量,其他卡客运量,总客运量
0,3275,9616900721642849,11,20220611142655,0.0,11,1,62655,20220611,50000,0,0,0
58,1610,9616900721753777,101,20220611131126,1.6,710,71,51126,20220611,50000,1,1,2
57,344,9616900722241657,6,20220612003114,0.0,700,70,923114,20220611,50000,0,0,0
56,3998,9616900721644930,6,20220611213845,0.0,680,68,133845,20220611,50000,0,0,0
55,2091,9616900722183756,101,20220611141133,1.6,660,66,61133,20220611,50000,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2091,9616900722183756,101,20220611141133,1.6,660,66,61133,20220611,233000,0,0,0
56,3998,9616900721644930,6,20220611213845,0.0,680,68,133845,20220611,233000,0,0,0
57,344,9616900722241657,6,20220612003114,0.0,700,70,923114,20220611,233000,0,0,0
59,7768,0,101,20220611145534,1.6,720,72,65534,20220611,233000,0,0,0
163,19508,9616900730122693,6,20220611230256,1.5,6270,627,150256,20220611,233000,0,0,0

In [77]:

ALL=ALL.loc[:,['段开始时间','线路编号','老年卡客运量','其他卡客运量','总客运量']]
ALL['30min开始时间']=0
for i in range(0,len(ALL)):
    T=ALL['段开始时间'].iloc[i]
    t=str(T)
    if len(t)==5:
        TS=t[-2:]
        TM=t[-4:-2]
        TH=t[0]
    if len(t)==6:
        TS=t[-2:]
        TM=t[-4:-2]
        TH=t[:2]
    t=TH+'：'+TM+'：'+TS
    ALL['30min开始时间'].iloc[i]=t

In [78]:
ALL

      段开始时间  线路编号  老年卡客运量  其他卡客运量  总客运量 30min开始时间
0     50000     1       0       0     0   5：00：00
1     50000     2       0       0     0   5：00：00
2     50000     3       0       0     0   5：00：00
3     50000     5       0       0     0   5：00：00
4     50000     6       0       0     0   5：00：00
..      ...   ...     ...     ...   ...       ...
159  233000   385       0       0     0  23：30：00
160  233000   387       0       0     0  23：30：00
161  233000   612       0       0     0  23：30：00
162  233000   622       0       0     0  23：30：00
163  233000   627       0       0     0  23：30：00

[6560 rows x 6 columns]

In [80]:
ALL.to_excel(r'F:\扬州\30min刷卡统计_11(1).xlsx')